name: Cloudflared
version: 4.1.1
slug: cloudflared
description: Use a Cloudflare Tunnel to remotely connect to Home Assistant without
  opening any ports
url: https://github.com/smarthomecomkh/hasaddon/cloudflared/
codenotary: dev@brenner.tech
init: false
hassio_api: true
hassio_role: homeassistant
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
map:
- ssl:rw
- share:rw
- config:rw
options:
  external_hostname: ''
  additional_hosts: []
schema:
  external_hostname: str?
  additional_hosts:
  - hostname: str
    service: str
    disableChunkedEncoding: bool?
  tunnel_name: 28b
  tunnel_token: d4242b4d-b8dc-4376-a4d5-851820a20510
  post_quantum: bool?
  catch_all_service: str?
  nginx_proxy_manager: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
image: ghcr.io/brenner-tobias/cloudflared/{arch}
